name: Release and Publish

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
  perform-release:
    name: Perform a release

    runs-on: ubuntu-latest

    steps:

        # Some steps for learning and for debug
        - name: GITHUB_EVENT_PATH (debug)
          run: cat $GITHUB_EVENT_PATH
        #- name: github.event.issue.pull_request (debug)
        #  env:
        #      PR: ${{ toJSON(github.event.issue.pull_request) }}
        #  run: echo "-- $PR --"
        #- name: github.event.comment.body (debug)
        #  env:
        #      COMMENT: ${{ toJSON(github.event.comment.body) }}
        #  run: echo "-- $COMMENT --"
        #- name: curl pull request url (debug)
        #  run: curl -s -X GET ${{ github.event.issue.pull_request.url }}

        - name: Show release tag
          run: echo ${{ github.event.release.tag_name }}

        # Checkout the tip of main
        - name: Checkout main
          uses: actions/checkout@v2

        - name: Git show
          run: git show --summary

        # Setup Java 11
        - name: Setup adopt java 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: 'gradle'

        - name: Validate gradle wrapper
          uses: gradle/wrapper-validation-action@v1

        - name: Build and Test
          uses: gradle/gradle-build-action@v2
          with:
              arguments: |
                  --info
                  --console=plain
                  --no-daemon
                  build

        - name: publishToMavenLocal
          if: success()
          uses: gradle/gradle-build-action@v2
          env:
              ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
              ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
              ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          with:
              arguments: |
                  --info
                  --console=plain
                  --no-daemon
                  publishToMavenLocal
                  -Pversion=${{ github.event.release.tag_name }}
                  -PsignPublication=true

        - name: Display tree of mavenLocal
          if: success()
          run: tree ~/.m2/repository/io/github/jrestclients


        - name: publishToSonatype and closeSonatypeStagingRepository
          if: success()
          uses: gradle/gradle-build-action@v2
          env:
              ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
              ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
              ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
              ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
              ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

          with:
              arguments: |
                  --info
                  --console=plain
                  --no-daemon
                  publishToSonatype
                  closeSonatypeStagingRepository
                  -Pversion=${{ github.event.release.tag_name }}
                  -PsignPublication=true

        # Additional steps are needed to update the documentation
