name: Release and Publish

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
  perform-release:
    name: Perform a release

    runs-on: ubuntu-latest

    steps:

        # Some steps for learning and for debug
        - name: GITHUB_EVENT_PATH (debug)
          run: cat $GITHUB_EVENT_PATH
        #- name: github.event.issue.pull_request (debug)
        #  env:
        #      PR: ${{ toJSON(github.event.issue.pull_request) }}
        #  run: echo "-- $PR --"
        #- name: github.event.comment.body (debug)
        #  env:
        #      COMMENT: ${{ toJSON(github.event.comment.body) }}
        #  run: echo "-- $COMMENT --"
        #- name: curl pull request url (debug)
        #  run: curl -s -X GET ${{ github.event.issue.pull_request.url }}

        # Checkout the tip of main
        - name: Checkout main
          uses: actions/checkout@v2

        - name: Git show
          run: git show --summary

        # Setup Java 11
        - name: Setup adopt java 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: 'gradle'

        - name: Build, test and publishToMavenLocal
          run: |
              chmod +x gradlew
              ./gradlew --version
              ./gradlew test publishToManveLocal --console=plain --no-daemon --scan

